### ISSUE TITLE
Address Overflow causes JavaScript Error

### ISSUE THREAD

**Issue by jos0003** [cyderize/MARIE.js#24]
This following MARIE code causes JavaScript to throw an error.

    Load x
    Add one
    Store x
    LoadI x
    x, HEX FFF
    one, DEC 0

This error arises when you run this code.
> Uncaught TypeError: Cannot read property 'classList' of null

**Comment by cyderize** [comment]
Yeah, that's because I haven't done bounds checking yet. I'll fix that and the overflow behaviour now.

**Comment by jos0003** [comment]
Yeah that should be ```one, DEC 1```.
